import { chromium } from '/Users/juliuscallahan/Desktop/Claude Code/rot-gt-calculator/tools/node_modules/playwright/index.mjs';
import { readFile } from 'node:fs/promises';
const css = await readFile('/Users/juliuscallahan/Desktop/Claude Code/rot-gt-calculator/kalkylator/v1/style.css', 'utf8');
const browser = await chromium.launch(); const page = await browser.newPage();
await page.setContent('<!doctype html><html><head></head><body></body></html>');
const r = await page.evaluate((css) => {
  const st = document.createElement('style'); st.textContent = css; document.head.append(st);
  const sheet = st.sheet; const dropped = []; const decls = [];
  const walk = (rules) => { for (const rule of rules) { if (rule.cssRules && !(rule instanceof CSSStyleRule)) walk(rule.cssRules); if (rule instanceof CSSStyleRule) { decls.push(rule.selectorText + ' -> ' + rule.style.length + ' decl'); } } };
  walk(sheet.cssRules);
  // compare declaration counts against source: count "prop:" occurrences inside each block roughly
  const src = css.replace(/\/\*[\s\S]*?\*\//g, ''); const blocks = src.match(/\{[^{}]*\}/g) || []; let srcDecl = 0; for (const b of blocks) srcDecl += (b.match(/[a-z-]+\s*:/g) || []).length;
  let parsedDecl = 0; const walk2 = (rules) => { for (const rule of rules) { if (rule.cssRules && !(rule instanceof CSSStyleRule)) walk2(rule.cssRules); if (rule instanceof CSSStyleRule) parsedDecl += rule.style.length; } }; walk2(sheet.cssRules);
  // detect dropped declarations: for each source block, check each prop exists in some parsed rule with the same selector
  const bySel = {}; const walk3 = (rules) => { for (const rule of rules) { if (rule.cssRules && !(rule instanceof CSSStyleRule)) walk3(rule.cssRules); if (rule instanceof CSSStyleRule) { bySel[rule.selectorText] = (bySel[rule.selectorText] || []).concat([...rule.style].map(p => p)); } } }; walk3(sheet.cssRules);
  const re = /([^{}]+)\{([^{}]*)\}/g; let m; const missing = [];
  while ((m = re.exec(src))) { const sel = m[1].trim().replace(/^[^\n]*\n\s*/, ''); if (sel.startsWith('@')) continue; const props = [...m[2].matchAll(/([a-z-]+)\s*:/g)].map(x => x[1]);
    const parsed = Object.entries(bySel).find(([s]) => s.replace(/\s+/g, ' ') === sel.replace(/\s+/g, ' ')); if (!parsed) { missing.push('RULE DROPPED: ' + sel); continue; }
    for (const p of props) { const longhands = parsed[1]; const ok = longhands.some(l => l === p || l.startsWith(p + '-') || (p === 'margin' && l.startsWith('margin')) || (p === 'padding' && l.startsWith('padding')) || (p === 'border' && l.startsWith('border')) || (p === 'background' && l.startsWith('background')) || (p === 'gap' && /gap/.test(l)) || (p === 'flex' && l.startsWith('flex')) || (p === 'animation' && l.startsWith('animation')) || (p === 'inset' && /top|left|right|bottom/.test(l)) || p.startsWith('--') || (p === 'font' && l.startsWith('font')) || (p==='padding-inline' && /padding-(left|right)/.test(l)) || (p==='padding-block' && /padding-(top|bottom)/.test(l)) || (p==='margin-block' && /margin-(top|bottom)/.test(l)) || (p==='min-inline-size' && l==='min-width') || (p==='column-gap' && l==='column-gap') || (p==='grid-row' && l.startsWith('grid-row')) || (p==='border-radius' && l.includes('radius')) || (p==='border-left' && l.startsWith('border-left')) || (p==='border-top' && l.startsWith('border-top')) || (p==='container-type' && l==='container-type') || (p==='text-wrap' && l.startsWith('text-wrap')) || (p==='white-space' && l.startsWith('white-space')) || (p==='transform' && l==='transform') || (p==='grid-template-columns' && l==='grid-template-columns') || (p==='grid-template-rows' && l==='grid-template-rows') || (p==='grid-auto-columns' && l==='grid-auto-columns') || (p==='overflow' && l.startsWith('overflow')) || (p==='visibility' && l==='visibility') || (p==='pointer-events' && l==='pointer-events') || (p==='letter-spacing' && l==='letter-spacing') || (p==='line-height' && l==='line-height') || (p==='text-align' && l==='text-align') || (p==='max-width' && l==='max-width') || (p==='min-width' && l==='min-width') || (p==='min-height' && l==='min-height') || (p==='width' && l==='width') || (p==='height' && l==='height') || (p==='fill' && l==='fill') || (p==='display' && l==='display') || (p==='opacity' && l==='opacity') || (p==='color' && l==='color') || (p==='top' && l==='top') || (p==='right' && l==='right') || (p==='position' && l==='position') || (p==='align-items' && l==='align-items') || (p==='align-self' && l==='align-self') || (p==='justify-content' && l==='justify-content') || (p==='flex-direction' && l==='flex-direction') || (p==='flex-wrap' && l==='flex-wrap')); if (!ok) missing.push(sel + ' :: ' + p); } }
  return { rules: sheet.cssRules.length, srcDecl, parsedDecl, missing: [...new Set(missing)] };
}, css);
console.log(JSON.stringify(r, null, 1)); await browser.close();
