import { chromium } from '../tools/node_modules/playwright/index.mjs';
import { createServer } from 'http'; import { readFile, stat } from 'fs/promises'; import { join, extname, resolve, dirname } from 'path'; import { fileURLToPath } from 'url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const mime = { '.html':'text/html; charset=utf-8', '.css':'text/css', '.js':'text/javascript', '.woff2':'font/woff2' };
const server = createServer(async (req,res)=>{ try { let p=join(root, decodeURIComponent(new URL(req.url,'http://x').pathname)); if((await stat(p)).isDirectory()) p=join(p,'index.html'); res.writeHead(200,{'content-type':mime[extname(p)]||'application/octet-stream'}); res.end(await readFile(p)); } catch { res.writeHead(404); res.end(); } });
await new Promise(r=>server.listen(8123,r));
const b = await chromium.launch(); const page = await b.newPage({ viewport:{width:390,height:844}, deviceScaleFactor:2 });
const errs=[]; page.on('pageerror',e=>errs.push(String(e))); page.on('console',m=>{ if(m.type()==='error') errs.push(m.text()); });
await page.goto('http://localhost:8123/kalkylator/index.html', { waitUntil:'networkidle' });
const read = async () => ({ rot: (await page.textContent('#rk-rot')).replace(/\s+/g,' ').trim(), gt: (await page.textContent('#rk-gt')).replace(/\s+/g,' ').trim(), not: await page.isHidden('#rk-rot-not') ? null : (await page.textContent('#rk-rot-not')).trim(), stopp: await page.isHidden('#rk-stopp') ? null : (await page.textContent('#rk-stopp')).trim() });
const out = {};
out.start = await read();
await page.fill('#rk-inkomst', '180000'); out.lon180k = await read();
await page.fill('#rk-inkomst', '300000'); out.lon300k = await read();
await page.fill('#rk-inkomst', '600000'); out.lon600k = await read();
await page.click('label:has(input[name="typ"][value="pension"])'); await page.fill('#rk-inkomst', '240000'); out.pension240k = await read();
await page.click('label:has(input[name="aldre"][value="nej"])'); out.aldreNej = await read();
await page.click('label:has(input[name="ager"][value="nej"])'); out.agerNej = await read();
await page.click('label:has(input[name="ager"][value="ja"])'); await page.click('label:has(input[name="aldre"][value="ja"])'); await page.click('label:has(input[name="typ"][value="lon"])'); await page.fill('#rk-inkomst', '300000');
await page.screenshot({ path: '_shots/v2-probe-mobile.png', fullPage: true });
const h = await page.evaluate(() => document.querySelector('#avdragskollen').getBoundingClientRect().height);
const fs = await page.evaluate(() => ({ etikett: getComputedStyle(document.querySelector('.rk__etikett')).fontSize, tal: getComputedStyle(document.querySelector('.rk__tal')).fontSize, chip: document.querySelector('.rk__segment label').getBoundingClientRect().height }));
out.mobil = { kortHojd: Math.round(h), ...fs, errs };
await b.close(); server.close(); console.log(JSON.stringify(out, null, 1));
