/* Riktade skärmdumpar av de värsta fynden ur enhetsmatrisen + montage.
   Kör: node tools/enhetsmatris-fynd.mjs  -> research/underlag/enheter/fynd/F*.jpg + montage-varsta-fynd.jpg */
import { chromium, webkit, devices } from '/Users/juliuscallahan/Desktop/Claude Code/rot-gt-calculator/tools/node_modules/playwright/index.mjs';
import { createServer } from 'node:http';
import { readFile, stat, writeFile } from 'node:fs/promises';
import { join, extname, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ut = join(root, 'research/underlag/enheter');
const mime = { '.html': 'text/html; charset=utf-8', '.css': 'text/css', '.js': 'text/javascript', '.woff2': 'font/woff2', '.jpg': 'image/jpeg' };
const v1Html = await readFile(join(root, 'kalkylator/v1/index.html'), 'utf8');
let artikelHtml = await readFile(join(root, 'kalkylator/artikel/index.html'), 'utf8');
artikelHtml = artikelHtml.replace(/<h2 class="ampy-h2 rk__rubrik"[^>]*>[\s\S]*?<\/h2>/, v1Html.match(/<h2 class="ampy-h2 rk__rubrik"[^>]*>[\s\S]*?<\/h2>/)[0]).replace(/<section class="ampy-card rk"[\s\S]*?<\/section>/, v1Html.match(/<section class="ampy-card rk"[\s\S]*?<\/section>/)[0]);
const server = createServer(async (req, res) => { try { const vag = decodeURIComponent(new URL(req.url, 'http://x').pathname); if (vag === '/kalkylator/artikel/index.html') { res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); res.end(artikelHtml); return; } let p = join(root, vag); if ((await stat(p)).isDirectory()) p = join(p, 'index.html'); res.writeHead(200, { 'content-type': mime[extname(p)] || 'application/octet-stream' }); res.end(await readFile(p)); } catch { res.writeHead(404); res.end(); } });
await new Promise((r) => server.listen(0, r)); const bas = `http://localhost:${server.address().port}`;
const hashar = { 'frontend-light-layer.min.css': '5b638592a2cd', 'theme-style-ampy.min.css': '243af2986dbc', 'post-15042.min.css': '502b0d84360f', 'post-56073.min.css': '69985dd214df', 'post-15096.min.css': '501d82d91edb' };
const cache = new Map();
async function ruta(route) { let url = route.request().url(); const m = url.match(/flying-press\/[0-9a-f]{12}\.(.+\.css)$/); if (m && hashar[m[1]]) url = url.replace(/flying-press\/[0-9a-f]{12}\./, `flying-press/${hashar[m[1]]}.`); let c = cache.get(url); if (!c) { try { const r = await route.fetch({ url, headers: { 'user-agent': 'Mozilla/5.0', accept: '*/*' } }); c = { status: r.status(), ct: r.headers()['content-type'] || 'application/octet-stream', body: await r.body() }; } catch { c = { status: 502, ct: 'text/plain', body: Buffer.from('') }; } cache.set(url, c); } await route.fulfill({ status: c.status, headers: { 'content-type': c.ct }, body: c.body }); }

const lab = (page, name, value) => page.locator(`#avdragskollen label:has(input[name="${name}"][value="${value}"])`);
async function klipp(page, sel, pad, fil, extra = {}) {
  const b = await page.locator(sel).first().boundingBox();
  const vw = page.viewportSize();
  const x = Math.max(0, b.x - pad), y = Math.max(0, b.y - pad);
  await page.screenshot({ path: join(ut, 'fynd', fil), type: 'jpeg', quality: 70, clip: { x, y, width: Math.min(vw.width - x, b.width + 2 * pad + (extra.extraW || 0)), height: Math.min(vw.height - y, b.height + 2 * pad + (extra.extraH || 0)) } });
}
const D = (n) => { const d = { ...devices[n] }; delete d.defaultBrowserType; return d; };
const FYND = [
  { fil: 'F1-ipad-gen7-hoger-segment-utanfor.jpg', rubrik: 'F1 Blocker: högerspalten 781–1115 px (iPad gen 7, 810 px). "Över 65" och "Båda" utanför kortet, sidan scrollar i sidled.', motor: webkit, ctx: D('iPad (gen 7)'), url: '/kalkylator/artikel/index.html?p=hoger&m=rot', steg: async (page) => { await page.evaluate(() => { const c = document.querySelector('#avdragskollen'); scrollTo(0, c.getBoundingClientRect().top + scrollY - 90); }); await page.waitForTimeout(150); await klipp(page, '#avdragskollen', 12, 'F1-ipad-gen7-hoger-segment-utanfor.jpg', { extraW: 80 }); } },
  { fil: 'F2-iphone-se-segment-utanfor.jpg', rubrik: 'F2 Major: 320 px (iPhone SE, Galaxy S9+). Trevägsvalet 3 × 88 px ryms inte: sista valet 7 px utanför kortet (15 px i artikeln).', motor: webkit, ctx: D('iPhone SE'), url: '/kalkylator/v1/index.html?m=rot', steg: async (page) => { await lab(page, 'alder-1', '66+').click(); await page.waitForTimeout(150); await klipp(page, '.rk__fraga--alder', 14, 'F2-iphone-se-segment-utanfor.jpg', { extraW: 20 }); } },
  { fil: 'F3-pixel7-hoger-gt-et-ensamt.jpg', rubrik: 'F3 Major: Pixel 7, artikel höger, grön teknik, Över 65 + Lön. Noten bryter "grön teknik-avdrag" / "et från." eftersom nowrap-spannet slutar före ändelsen.', motor: chromium, ctx: D('Pixel 7'), url: '/kalkylator/artikel/index.html?p=hoger&m=gt', steg: async (page) => { await lab(page, 'alder-1', '66+').click(); await page.locator('#rk-inkomst-1').fill('300000'); await page.locator('#rk-inkomst-1').blur(); await page.waitForTimeout(700); await page.locator('#rk-not').scrollIntoViewIfNeeded(); await page.evaluate(() => scrollBy(0, -120)); await page.waitForTimeout(150); await klipp(page, '.rk__panel', 6, 'F3-pixel7-hoger-gt-et-ensamt.jpg'); } },
  { fil: 'F4-galaxy-s8-rot-avdraget-bindestreck.jpg', rubrik: 'F4 Major: Galaxy S8 (360 px) fristående, Över 65 + Lön. Noten bryter "ROT-" / "avdraget" vid bindestrecket (29 av 156 kombinationer, alla tre motorer).', motor: chromium, ctx: D('Galaxy S8'), url: '/kalkylator/v1/index.html?m=rot', steg: async (page) => { await lab(page, 'alder-1', '66+').click(); await page.locator('#rk-inkomst-1').fill('300000'); await page.locator('#rk-inkomst-1').blur(); await page.waitForTimeout(700); await page.locator('#rk-not').scrollIntoViewIfNeeded(); await page.waitForTimeout(150); await page.locator('.rk__resultat').screenshot({ path: join(ut, 'fynd', 'F4-galaxy-s8-rot-avdraget-bindestreck.jpg'), type: 'jpeg', quality: 70 }); } },
  { fil: 'F5-desktop-1024-hoger-smal-spalt.jpg', rubrik: 'F5 Blocker (samma som F1) vid 1024 px: högerspalten är 287 px. "Över 65" och "Båda" klipps, etiketten bryter "ROT-" / "AVDRAG", "upp till" hamnar ovanför talet. Spalten når sina 384 px först vid 1361 px.', motor: chromium, ctx: { viewport: { width: 1024, height: 768 }, deviceScaleFactor: 2 }, url: '/kalkylator/artikel/index.html?p=hoger&m=rot', steg: async (page) => { await page.evaluate(() => { const c = document.querySelector('#avdragskollen'); scrollTo(0, c.getBoundingClientRect().top + scrollY - 80); }); await page.waitForTimeout(150); await klipp(page, '#avdragskollen', 12, 'F5-desktop-1024-hoger-smal-spalt.jpg', { extraW: 60 }); } },
  { fil: 'F6-artikel-marginaler-nollade.jpg', rubrik: 'F6 Major: värdsidans reset (.ampy p { margin: 0 }) nollar avstånden tal, "Per person och år.", disclaimer i artikeln, och stoppläget gör kortet 8 px högre. Vänster: fristående 390 px. Höger: artikeln 390 px.', motor: webkit, ctx: D('iPhone 12'), url: '/kalkylator/v1/index.html?m=rot', steg: async (page) => { await page.locator('.rk__panel').scrollIntoViewIfNeeded(); await page.waitForTimeout(100); await klipp(page, '.rk__panel', 0, 'F6a-fristaende-panel.jpg'); await page.goto(bas + '/kalkylator/artikel/index.html?p=hoger&m=rot', { waitUntil: 'load', timeout: 90000 }); await page.evaluate(() => document.fonts.ready); await page.locator('.rk__panel').scrollIntoViewIfNeeded(); await page.evaluate(() => scrollBy(0, -80)); await page.waitForTimeout(150); await klipp(page, '.rk__panel', 0, 'F6b-artikel-panel.jpg'); }, par: ['F6a-fristaende-panel.jpg', 'F6b-artikel-panel.jpg'] },
  { fil: 'F7-desktop-1280-topp-upp-till-egen-rad.jpg', rubrik: 'F7 Major: artikel överst, 1280 px (behållare 781 px, två spalter). Talet är 56 px (skärmstyrt) men panelen 350 px: "upp till" hamnar ovanför talet redan i standardläget; stoppläget flyttar etiketten 9 px.', motor: chromium, ctx: { viewport: { width: 1280, height: 800 }, deviceScaleFactor: 2 }, url: '/kalkylator/artikel/index.html?p=topp&m=rot', steg: async (page) => { await page.evaluate(() => { const c = document.querySelector('#avdragskollen'); scrollTo(0, c.getBoundingClientRect().top + scrollY - 90); }); await page.waitForTimeout(150); await klipp(page, '.rk__panel', 0, 'F7-desktop-1280-topp-upp-till-egen-rad.jpg'); } },
  { fil: 'F8-iphone-se-artikel-eyebrow-bindestreck.jpg', rubrik: 'F8 Minor: 320 px i artikeln. Etiketten bryter "DITT TILLGÄNGLIGA ROT-" / "AVDRAG" vid bindestrecket.', motor: webkit, ctx: D('iPhone SE'), url: '/kalkylator/artikel/index.html?p=topp&m=rot', steg: async (page) => { await page.locator('.rk__panel').scrollIntoViewIfNeeded(); await page.evaluate(() => scrollBy(0, -70)); await page.waitForTimeout(150); await klipp(page, '.rk__panel', 0, 'F8-iphone-se-artikel-eyebrow-bindestreck.jpg'); } },
  { fil: 'F9-desktop-1440-topp-rad-bryter.jpg', rubrik: 'F9 Minor: artikel överst 1366–1920 px (behållare 832). "ROT och RUT du redan använt i år" ryms inte bredvid fältet: fältet faller ner till vänster medan raden ovanför är inline.', motor: chromium, ctx: { viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 }, url: '/kalkylator/artikel/index.html?p=topp&m=rot', steg: async (page) => { await page.evaluate(() => { const c = document.querySelector('#avdragskollen'); scrollTo(0, c.getBoundingClientRect().top + scrollY - 90); }); await page.waitForTimeout(150); await klipp(page, '.rk__fragor', 0, 'F9-desktop-1440-topp-rad-bryter.jpg'); } },
];
const oppna = new Map();
for (const f of FYND) {
  const br = oppna.get(f.motor) || (await f.motor.launch()); oppna.set(f.motor, br);
  const ctx = await br.newContext({ ...f.ctx, reducedMotion: 'reduce', locale: 'sv-SE' }); await ctx.route(/^https:\/\/ampy\.se\//, ruta); await ctx.route(/^https:\/\/(www\.googletagmanager|fonts\.g|www\.google-analytics|connect\.facebook)/, (r) => r.abort());
  const page = await ctx.newPage();
  await page.goto(bas + f.url, { waitUntil: 'load', timeout: 90000 }); await page.evaluate(() => document.fonts.ready); await page.waitForTimeout(200);
  try { await f.steg(page); console.log('ok', f.fil); } catch (e) { console.log('FEL', f.fil, String(e).slice(0, 200)); }
  await ctx.close();
}
/* montage: HTML-sida med bilderna, renderad i Chromium */
const br = oppna.get(chromium) || (await chromium.launch());
const page = await br.newPage({ viewport: { width: 1600, height: 1200 }, deviceScaleFactor: 1 });
const kort = FYND.map((f) => { const bilder = (f.par || [f.fil]).map((b) => `<img src="${bas}/research/underlag/enheter/fynd/${b}">`).join(''); return `<figure><div class="b">${bilder}</div><figcaption>${f.rubrik}</figcaption></figure>`; }).join('');
await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0;background:#f5f9ff;font:14px/1.4 -apple-system,system-ui,sans-serif;color:#090b32;padding:24px}h1{font-size:20px;margin:0 0 16px}.g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}figure{margin:0;background:#fff;border:1px solid rgba(9,11,50,.14);border-radius:12px;padding:12px;display:flex;flex-direction:column;gap:10px}.b{display:flex;gap:8px;align-items:flex-start;justify-content:center;background:#eef1f7;border-radius:8px;padding:8px;min-height:120px}img{max-width:100%;max-height:520px;height:auto;object-fit:contain;flex:1 1 0;min-width:0}figcaption{font-size:13px}</style></head><body><h1>Avdragskollen: värsta fynden i enhetsmatrisen (26 konfigurationer × 6 sidor × 9 tillstånd, 2026-09-20)</h1><div class="g">${kort}</div></body></html>`, { waitUntil: 'load' });
await page.waitForTimeout(800);
await page.screenshot({ path: join(ut, 'montage-varsta-fynd.jpg'), type: 'jpeg', quality: 72, fullPage: true });
console.log('montage klart');
for (const b of oppna.values()) await b.close();
server.close();
